# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on: workflow_dispatch 

jobs:
  ci:
    strategy:
      matrix:
        include:
          - {os: macOS-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Dependencies
        run: ./run.sh install_all

      - name: Build binary package
        run:  R CMD INSTALL --build 

      - uses: actions/upload-artifact@v3
        with:
          name: macOS package
          path: '*.tgz'
          retention-days: 1
